### ISSUE TITLE
Crash when missing cmd /c in .rtext

### ISSUE THREAD

**Issue by hbragge** [sanastasiou/RTextNpp#25]
Getting unhandled .net exception when missing "cmd /c" in front of the command in .rtext and trying to load the model:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_HasExited()
   at RTextNppPlugin.RText.RTextBackendProcess.get_HasExited()
   at RTextNppPlugin.RText.ConnectorManager.<CreateConnector>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)

**Comment by sanastasiou** [comment]
Fixed with de2063ff6261e140603310450e148436977e19c5
